### ISSUE TITLE
Registration Page

### ISSUE THREAD

**Issue by aashishxetri5** [aashishxetri5/YouWrite#5]
### Details

- Fullname
- Email
- Password
- Confirm Password

**Comment by Aman0786-git** [comment]
can you assign me this

**Comment by rishabhknowss** [comment]
please assign the task

**Comment by aashishxetri5** [comment]
Hi @rishabhknowss, Thank you for showing interest. Unfortunately the wireframing for the registration page is yet to be done. This will take some time.
